### ISSUE TITLE
where Tapo hubs must be added by IP address?

### ISSUE THREAD

**Issue by blassox** [zmx264/homebridge-kasa-hub#2]
There is no config.json sample to add this plugin to HB.
Can you help me?

**Comment by zmx264** [comment]
You can use the UI to configure the plugin: see Plugin Config menu.
Bellow you can find a sample config.

```
{
    "devices": [
        "192.168.1.10"
    ],
    "email": "*****",
    "password": "****",
    "platform": "KasaHub"
}
```
